const oracleArr = [
    "Eine Begegnung bringt die Inspiration für ein neues Projekt.",
    "Aus dem Chaos wird ein Stern geboren. ",
    "Du kannst deinen Lügen nicht entfliehen. Bleibe bei der Wahrheit, auch wenn sie schmerzt.",
    "Deine Quelle der Kraft begegnet dir im Traum.",
    "Achte auf die Bäume. In einem findest du deinen engsten Freund.",
    "Begib dich auf Visionssuche – die Geister kennen deine Bestimmung.",
    "Lasse die Lust in dein Leben in allen erdenklichen Formen.",
    "Dein Glück liegt in der Zufriedenheit, nicht der Leidenschaft.",
    "Integriere Meditation in dein tägliches Leben und du wirst Klarheit erlangen.",
    "Du kannst Liebe nicht besitzen, nur tun.",
    "Finde deine Aufgabe für die Gemeinschaft. Worin kannst du dienen?",
    "Vertraue auf deine Intuition.",
    "Du darfst Fehler machen. Verzeihe dir.",
    "In der Kreativität liegt die Magie. Suche dir ein Medium, um sie fließen zu lassen.",
    "Passe deinen Rhythmus dem Lauf der Sonne an, wenn es dir möglich ist.",
    "Feiere die Jahreskreisfeste!",
    "Finde oder gründe deine Gemeinschaft.",
    "Lebe dein Leben in vollen Zügen! Du kannst es nicht nachholen.",
    "Du findest Liebe, wo du sie am wenigsten erwartest.",
    "Die Lösung liegt im Detail.",
    "Baue einen Tempel.",
    "Schreibe ein Buch.",
    "Externalisiere und dann befreunde dich mit deinen Dämonen.",
    "Lies ein Buch, das du normalerweise nicht lesen würdest.",
    "Erkenne und verteidige deine Grenzen.",
    "Eitelkeit schränkt dich ein.",
    "Erkenne, dass alles im Fluss ist und vertraue.",
    "Immer mehr bringt dir am Ende nichts.",
    "Übe dich täglich in Dankbarkeit und du wirst zufrieden sein.",
    "Strebe nach Weisheit.",
    "In der Ruhe liegt die Kraft. Verbringe täglich eine viertel Stunde in vollkommener Ungestörtheit.",
    "Setze dich für die Rechte aller Menschen ein.",
    "Sei nicht zu schnell mit deinem Urteil über andere.",
    "Schaue auf die Welt mit Kinderaugen. Dann siehst du die Lösung deines Problems.",
    "Zweifle nicht an der Wirkung von Magie. Deine Zweifel behindern jeden Zauber.",
    "Mache einen magischen Hausputz und opfere den guten Geistern deines Hauses.",
    "Die Antwort erreicht dich bald.",
    "Warte bis die Frucht reif ist, bevor du sie erntest.",
    "In der Anderswelt erwartet dich ein Wesen, das dich zu lehren vermag.",
    "Moral ist eine Einheitsgröße. Entscheide selbst, was gut ist und was schlecht.",
    ,
    "Höre auf deinen Körper. Er ist ein Spiegelbild deiner Seele.",
    "Den Gerechten wird Recht geschehen.",
    "Dein Herz kennt deine Berufung.",
    "Du selbst bist Erschaffer*in deiner Wirklichkeit. Ist sie nach deinem Geschmack?",
    "Die Mondin wird dich führen.",
    "Lass das Element Wasser in dein Leben. Welche seiner Qualitäten fehlen dir?",
    "Lass das Element Feuer in dein Leben. Welche seiner Qualitäten fehlen dir?",
    "Lass das Element Erde in dein Leben. Welche seiner Qualitäten fehlen dir?",
    "Lass das Element Luft in dein Leben. Welche seiner Qualitäten fehlen dir?",
    "Lerne, deinen Geist mit dem Universellen Geist zu verbinden.",
    "Höre den Ruf der Geister.",
    "Dein Krafttier wird dich finden",
    "Gehe für eine Weile den Weg des Eremiten.",
    "Gehe den Weg der Klarheit. Welche Filter kannst du entfernen? Was vernebelt deinen Geist? Welche Schleider kannst du lüften?",
    "Auf welchem Ohr bist du taub?",
    "Welche Rolle möchtest du in deinem Leben spielen?",
    "Auf welchem Auge bist du blind?",
    "Konzentriere dich auf dein Wesentliches.",
    "Nur im Dunkeln kannst du erkennen.",
    "Wo Licht ist, ist auch Schatten.",
    "Willst du haben oder sein?",
    "Lies „Die Kunst des Liebens“ von Erich Fromm",
    "Dein Schatten gehört zu dir. Lerne ihn kennen.",
    "Du kannst Großes schaffen.",
    "Die Große Mutter spendet dir Trost. Suche ihren Schoß.",
    "Entferne elektrische Gerate aus deinem Schlafzimmer.",
    "Warte nicht mehr. Beginne.",
    "Du darfst dich entfalten.",
    "Du darfst frei sein.",
    "Du darfst es leicht nehmen.",
    "Sei Göttin/Gott deines Lebens.",
    "Finde deine Balance.",
    "Nutze deinen Einfluss weise.",
    "Bringe Menschen uneigennützig zusammen, die sich etwas geben können.",
    "Menschen haben keine Batterien. Sorge für ein artgerechtes Leben.",
    "Höre genau hin und höre zu.",
    "Durch welche Brille siehst du die Welt? Was passiert, wenn du sie absetzt?",
    "Magie zu wirken erfordert Übung und Disziplin.",
    "Ein Hexenzirkel wird die Gemeinschaft sein, nach der du dich sehnst.",
    "Göttinnen und Götter senden dir Zeichen, wenn sie in deinem Leben sein sollten.",
    "Dein Körper ist dein Tempel.",
    "Liebe, wen du willst.",
    "Lass dich nicht von Geschlechternormen einschränken.",
    "Huldige der großen Bärin.",
    "Lass deine Masken fallen.",
    "Lerne eine neue magische Technik.",
    "Dogmatismus ist ein Gefängnis.",
    "Zwischen den Zeilen ist die Nachricht verborgen.",
    "Es gibt keine Wahrheit.",
    "Deine Wahrheit gilt nur in deiner Wirklichkeit.",
    "Alles ist mit allem verbunden.",
    "Zeit ist nur ein Konzept.",
    "Toleranz wird Frieden bringen.",
    "Öffne dein drittes Auge beim Sex.",
    "Du wirst fantastischen Sex haben.",
    "Selbstliebe ist Tun.",
];

export default oracleArr;
